name: Generate Snake
on:
  schedule:
    - cron: "42 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Snake-SVG
        uses: Platane/snk/svg-only@v2
        id: snake-svg
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            
      - name: for debugging
        run: git status
        
      - name: Publish
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # using output branch avoids cluttering main
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
